angular.module('Hartville_io').controller(
	'MainController', ['$scope',function($scope){
		$scope.navbar = [
		{
			display:"home",
			url:"#/",
		},
		{
			display:"about",
			url:"#/about/",
		},
		{
			display:"blog",
			url:"#/blog/",
		},
		{
			display:"spotlight",
			url:"#/spotlight/",
		},
		{
			display:"events",
			url:"#/events/",
		},
		{
			display:"community",
			url:"#/community/",
		},
        ];
	}]);